config/routes.rb
Rails.application.routes.draw do

  scope :auth do
    get 'is_signed_in', to: 'auth#is_signed_in?'
  end

  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :products do
        resources :prices
      end
    end
  end

  root to: 'home#index'
  get '*path', to: 'home#index'

end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :url, presence: true
  validates :url, format: { with: URI.regexp }, if: Proc.new { |a| a.url.present? }
  validates :aim_price, numericality: { only_integer: true }

  has_many :prices
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/api/v1/prices_controller.rb
class Api::V1::PricesController < ApplicationController
  respond_to :json
  before_action :set_price, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /product/:product_id/prices
  # GET /product/:product_id/prices.json
  def index
    logger.debug "I'm here" 
    @product = Product.find(params[:product_id])

    respond_to do |format|
      format.json { render json: { error: ['No such product'] } } unless @product
      format.json { render json: { error: ['This user doesn\'t posess this product'] } } unless current_user.products.include? @product

      format.json { render json: @product.prices }
    end 
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:price, :product_id)
    end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  respond_to :json
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /products
  # GET /products.json
  def index
    respond_with current_user.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.create(product_params)

    respond_to do |format|
      if current_user.save
        format.json { render json: @product }
      else
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.json { render :show, status: :ok, location: @product }
      else
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      result = params.require(:product).permit(:url, :aim_price, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :provider
    devise_parameter_sanitizer.for(:sign_up) << :uid
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def is_signed_in?
    if user_signed_in?
      render :json => {"signed_in" => true, "user" => current_user}.to_json
    else
      render :json => {"signed_in" => false}.to_json
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.slim
-content_for :title do
  'PriceChecker

= react_component 'App'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta content= "text/html; charset=UTF-8" http-equiv="Content-Type" /
    meta charset= "utf-8" /
    meta content= "width=de ice-width, initial-scale=1.0" name= "viewport" /
    title
      =content_for?(:title) ? yield(:title) : "foundation-rails"
    =stylesheet_link_tag    "application"
    =javascript_include_tag "vendor/modernizr"
    =javascript_include_tag "application"
    =csrf_meta_tags
  body
    ==yield

app/views/prices/_form.html.slim
= simple_form_for(@price) do |f|
  = f.error_notification

  .form-inputs
    = f.input :price

  .form-actions
    = f.button :submit

app/views/prices/edit.html.slim
h1 Editing price

== render 'form'

= link_to 'Show', @price
'|
= link_to 'Back', prices_path

app/views/prices/index.html.slim
h1 Listing prices

table
  thead
    tr
      th Price
      th
      th
      th

  tbody
    - @prices.each do |price|
      tr
        td = price.price
        td = link_to 'Show', price
        td = link_to 'Edit', edit_price_path(price)
        td = link_to 'Destroy', price, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Price', new_price_path

app/views/prices/new.html.slim
h1 New price

== render 'form'

= link_to 'Back', prices_path

app/views/prices/show.html.slim
p#notice = notice

p
  strong Price:
  = @price.price

= link_to 'Edit', edit_price_path(@price)
'|
= link_to 'Back', prices_path

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :aim_price
    = f.number_field :aim_price
  .field
    = f.label :description
    = f.text_field :description
  .actions = f.submit

app/views/products/edit.html.slim
.row.full_width
  .medium-8.medium-centered.column
    h1 Editing product

    == render 'form'

    = link_to 'Show', @product
    '|
    = link_to 'Back', products_path

app/views/products/index.html.slim
.row.full_width
  .medium-8.medium-centered.column
    h1 Listing products

    table
      thead
        tr
          th Url
          th Aim price
          th Description
          th
          th
          th

      tbody
        - @products.each do |product|
          tr
            td = product.url
            td = product.aim_price
            td = product.description
            td = link_to 'Show', product
            td = link_to 'Edit', edit_product_path(product)
            td = link_to 'Destroy', product, data: {:confirm => 'Are you sure?'}, :method => :delete

    br

    = link_to 'New Product', new_product_path

app/views/products/new.html.slim
.row.full_width
  .medium-8.medium-centered.column
    h1 New product

    == render 'form'

    = link_to 'Back', products_path

app/views/products/show.html.slim
.row.full_width
  .medium-8.medium-centered.column
    p#notice =notice

    p
      strong Url:
      = @product.url
    p
      strong Aim price:
      = @product.aim_price
    p
      strong Description:
      = @product.description

    = link_to 'Edit', edit_product_path(@product)
    '|
    = link_to 'Back', products_path